print("""
      Monday.         Tuesday.         Wednesday.       Thursday.        Friday.          
      Egnlish.        Algebra II.      History.          Art.            Spanish III.          
      Spanish III.    Research         Diologue.        English.         Chemistry.       
      History.        Intro Comp Sci   Spanish III      Chemistry.       English.
      Lunch .          Lunch.           Lunch.           Lunch.           Lunch.                     
      Office Hours.    Chemistry.       Art.             Algebra II.      History.
research princples.    Spanish III.     Algebra II.      Community Time.  Comunity Time.
                       Egnlish.                          History.         Comp Sci.                         
      """)